defaults: &defaults
  adapter: postgresql
  encoding: UTF-8
  min_messages: warning
  username: sims
  password: lti18

localhost: &localhost
  host: localhost
  port: 5432

# store: &store
#   host: store.smartesting.com
#   port: 46020

development:
  <<: *defaults
  <<: *localhost
  database: sims_development
  pool: 5

production:
  <<: *defaults
  <<: *store
  database: sims_production
  pool: 5

test:
  <<: *defaults
  <<: *localhost
  database: sims_test
  pool: 5