defaults: &defaults
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  username: 
  password: 

store: &store
  host: 
  port: 5432

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter:  postgresql
  encoding: unicode
  pool: 5
  database: 
  username: 
  password: 
  host: 
  port: 5432

# production:  
  # <<: *defaults
  # <<: *store
  # database: d9hqk0dtokmtui
  # pool: 5

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
