defaults: &defaults
  adapter: postgresql
  encoding: UTF-8
  min_messages: warning
  username: jwblqbwocnwwmh
  password: vf7kCqQYwsnQ7Qv6EhPQNaz1JR

localhost: &localhost
  host: localhost
  port: 5432

store: &store
  host: ec2-54-243-241-130.compute-1.amazonaws.com
  port: 5432

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

# development:
#   <<: *defaults
#   <<: *localhost
#   database: sims_development
#   pool: 5

production:
  <<: *defaults
  <<: *store
  database: dfpajksm2gub22
  pool: 5

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
