defaults: &defaults
  adapter: postgresql
  encoding: UTF-8
  min_messages: warning
  username: axtppjywnxptci
  password: SF-EfdwkqbsUZRUn3ZMj7FGgcO

localhost: &localhost
  host: localhost
  port: 5432

store: &store
  host: ec2-54-243-238-144.compute-1.amazonaws.com
  port: 5432

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *defaults
  <<: *store
  database: dbaam93bv3kfkl
  pool: 5

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000